version: '3'
services:
  
  cache:
    restart: always
    image : redis
    ports:
      - 0.0.0.0:6379:6379

  db: 
    restart: always
    image: mongo
    ports:
      - 0.0.0.0:27017:27017

  backend:
    restart: always

    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ../../
    ports:
      - 0.0.0.0:7000:8080
    depends_on:
      - cache
      - db
    environment:
      - REDIS_HOST=cache
      - MONGO_HOST=db