version: '3'
services:

  cache:
    image : redis
    ports:
      - 127.0.0.1:6379:6379

  db:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017

  backend:
    build:
      dockerfile: ./docker/deploy/be/Dockerfile
      context: ../../
    depends_on:
      - db
      - cache
    environment:
      - REDIS_HOST=cache
      - MONGO_HOST=db

  proxy:
    build:
      dockerfile: ./docker/deploy/proxy/Dockerfile
      context: ../../
    ports:
      - 80:80
