version: '3'
services:

  cache:
    image : redis
    ports:
      - 6379:6379

  db:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build:
      dockerfile: ./docker/deploy/be/Dockerfile
      context: ../../
    depends_on:
      - db
      - cache

  proxy:
    build:
      dockerfile: ./docker/deploy/proxy/Dockerfile
      context: ../../
    ports:
      - 127.0.0.1:80:80
