version: '3'
services:
  
  cache:
    restart: always
    image : redis
    ports:
      - 127.0.0.1:6379:6379

  db: 
    restart: always
    image: mongo
    ports:
      - 127.0.0.1:27017:27017